clone_depth: 1
version: '{branch}.{build}'

image:
  - Visual Studio 2015
  - Visual Studio 2017
  - Visual Studio 2019

configuration:
  - Debug
  - Release

environment:
  bin_dir: $(APPVEYOR_BUILD_FOLDER)/build/$(configuration)/bin

platform:
  - Win32
  - x64

pull_requests:
  do_not_increment_build_number: true

install:
  - cmd: git submodule update --init --recursive

before_build:
  - ps: mkdir build
  - ps: cd build
  - ps: cmake .. -DCMAKE_GENERATOR_PLATFORM="$env:platform"

build:
  project: build/RenHook.sln
  verbosity: minimal

test_script:
  - ps: cd "$env:bin_dir"
  - ps: ./Tests.exe

artifacts:
  - path: build/$(configuration)/libs
    name: RenHook
    type: zip
